### ISSUE TITLE
Constant inputs, no output constraints - Marabou returns `unsat`

### ISSUE THREAD

**Issue by MatthewDaggitt** [NeuralNetworkVerification/Marabou#670]
**Steps to reproduce**: run the command `Marabou network.onnx query.txt` with the attached files

**Expected behaviour**: Marabou should return SAT as the query just sets every input to a constant value and doesn't have any constraints on the output.

**Actual behaviour**: Marabou returns `unsat`

[bug.zip](https://github.com/NeuralNetworkVerification/Marabou/files/12461587/bug.zip)

**Comment by digumx** [comment]
This is close to how #669 was found, by removing constraints from a query very similar to the one here.

**Comment by wu-haoze** [comment]
@MatthewDaggitt I just took a look and I think the issue is with the C++ onnx parser. In particular, I believe the issue is with the handling of the Add operation. Could you please look into this?

I loaded the network and the query using the python API and Marabou can find a counter-example without issue. I attach the script using the python API.

[python_api_test.zip](https://github.com/NeuralNetworkVerification/Marabou/files/12528281/python_api_test.zip)

**Comment by MatthewDaggitt** [comment]
Eek, that's embarrassing if true. I'll have a look. While I'm doing that, while you're in this zone, could you check #669 which appears to give similar behaviour, but using the Python front-end instead?

**Comment by MatthewDaggitt** [comment]
>  In particular, I believe the issue is with the handling of the Add operation.

@wu-haoze any chance you could elaborate why you think it's the Add operation in particular? Might save me some time!

**Comment by wu-haoze** [comment]
> > In particular, I believe the issue is with the handling of the Add operation.
> 
> @wu-haoze any chance you could elaborate why you think it's the Add operation in particular? Might save me some time!

Hi Matthew. I didn't look closely, but I suspect the issue lies in when Add adds a constant to the previous node and we achieves this by modifying existing equations.

**Comment by wu-haoze** [comment]
> Eek, that's embarrassing if true. I'll have a look. While I'm doing that, while you're in this zone, could you check #669 which appears to give similar behaviour, but using the Python front-end instead?

I just took a look and seems it's due to a different issue. We assume that each addend on the left hand side of an equation represents a unique variable.

**Comment by digumx** [comment]
Thanks @wu-haoze, issue #669 is solved, and it does indeed seem to be unrelated. Sorry for the confusion.

**Comment by wu-haoze** [comment]
The PR #716 does not fix this bug as I thought. I still felt the problem is in the Add operation in the onnx parser on the C++ side, because when I invoke the problem using the Python API using the following code, I get a sat solution. 

"""
from maraboupy import Marabou
network = Marabou.read_onnx("./network.onnx")
ipq = network.getMarabouQuery()
Marabou.solve_query(ipq, propertyFilename="./query.txt")
"""

**Comment by wu-haoze** [comment]
Thanks a lot! And no rush!
________________________________
